









from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 719)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 4, 4, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 2, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 2, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 4, 0, 1, 3)
        self.gridLayout_6.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_2.setProperty("value", 5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox.setMaximum(500)
        self.spinBox.setProperty("value", 30)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 6, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_3.setMaximum(100)
        self.spinBox_3.setProperty("value", 5)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_4.setMaximum(9999)
        self.spinBox_4.setProperty("value", 500)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 4, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 1, 0, 3, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 6, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_3.addWidget(self.toolButton_3, 2, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_3.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 5, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 5, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_5.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_5.addWidget(self.radioButton_5, 0, 1, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_5.addWidget(self.radioButton_6, 0, 2, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_5.addWidget(self.radioButton_7, 1, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_5.addWidget(self.radioButton_8, 1, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_5.addWidget(self.radioButton_9, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_10.setCheckable(True)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_8.addWidget(self.radioButton_10, 0, 0, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_8.addWidget(self.radioButton_11, 0, 1, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_8.addWidget(self.radioButton_12, 0, 2, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout_8.addWidget(self.radioButton_13, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_7, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "输出格式"))
        self.radioButton.setText(_translate("Form", "html"))
        self.pushButton_2.setText(_translate("Form", "确认文本名"))
        self.radioButton_2.setText(_translate("Form", "json"))
        self.radioButton_3.setText(_translate("Form", "null"))
        self.lineEdit_2.setText(_translate("Form", "默认则随机命名"))
        self.groupBox_5.setTitle(_translate("Form", "基本参数"))
        self.label_3.setText(_translate("Form", "设置Poc并发"))
        self.pushButton.setText(_translate("Form", "确认参数"))
        self.label_4.setText(_translate("Form", "Tcp连接的超时时间"))
        self.label.setText(_translate("Form", "单个请求最大允许的跳转数"))
        self.label_5.setText(_translate("Form", "每秒最大请求数"))
        self.pushButton_8.setText(_translate("Form", "高级设置"))
        self.label_2.setText(_translate("Form", "选择xray文件"))
        self.toolButton.setText(_translate("Form", "..."))
        self.groupBox_2.setTitle(_translate("Form", "启动"))
        self.label_8.setText(_translate("Form", "指定url列表文件"))
        self.label_6.setText(_translate("Form", "指定url"))
        self.pushButton_3.setText(_translate("Form", "开启主动扫描"))
        self.label_7.setText(_translate("Form", "指定request文件"))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.pushButton_9.setText(_translate("Form", "查看扫描结果"))
        self.groupBox_6.setTitle(_translate("Form", "其他"))
        self.pushButton_5.setText(_translate("Form", "查看xray版本"))
        self.pushButton_7.setText(_translate("Form", "编写POC"))
        self.pushButton_6.setText(_translate("Form", "清空命令行输出"))
        self.pushButton_10.setText(_translate("Form", "查看当前命令"))
        self.groupBox_4.setTitle(_translate("Form", "被动扫描"))
        self.label_9.setText(_translate("Form", "被动监听IP"))
        self.lineEdit_6.setText(_translate("Form", "127.0.0.1"))
        self.label_10.setText(_translate("Form", "被动监听端口"))
        self.pushButton_4.setText(_translate("Form", "开启被动扫描"))
        self.groupBox_3.setTitle(_translate("Form", "log level"))
        self.radioButton_4.setText(_translate("Form", "null"))
        self.radioButton_5.setText(_translate("Form", "debug"))
        self.radioButton_6.setText(_translate("Form", "info"))
        self.radioButton_7.setText(_translate("Form", "warn"))
        self.radioButton_8.setText(_translate("Form", "error"))
        self.radioButton_9.setText(_translate("Form", "fatal"))
        self.groupBox_7.setTitle(_translate("Form", "等级"))
        self.radioButton_10.setText(_translate("Form", "关"))
        self.radioButton_11.setText(_translate("Form", "中"))
        self.radioButton_12.setText(_translate("Form", "高"))
        self.radioButton_13.setText(_translate("Form", "严重"))
