









from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1304, 788)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 1, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_31.setChecked(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_5.addWidget(self.checkBox_31, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 1, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_5.addWidget(self.checkBox_32, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_2.addWidget(self.checkBox_16, 5, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout_2.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 10, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 10, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 6, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 9, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 2, 1, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_2.addWidget(self.checkBox_19, 8, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_2.addWidget(self.checkBox_18, 7, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 1, 1, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 4, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 6, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_8.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_5.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_8.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_8.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_7)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_8.addWidget(self.toolButton, 2, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_4.addWidget(self.checkBox_36, 3, 0, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_37.setChecked(True)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_4.addWidget(self.checkBox_37, 4, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_33.setChecked(True)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_4.addWidget(self.checkBox_33, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_35.setChecked(True)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_4.addWidget(self.checkBox_35, 2, 0, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_34.setChecked(True)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_4.addWidget(self.checkBox_34, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_6.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 1, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_3.addWidget(self.checkBox_29, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 2, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_3.addWidget(self.checkBox_27, 7, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 4, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 10, 1, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 6, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_3.addWidget(self.checkBox_30, 10, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 0, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_3.addWidget(self.checkBox_28, 8, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 11, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 11, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_7.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_7.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_6.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_9.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_10)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 1, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_10)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_9.addWidget(self.toolButton_3, 1, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_9.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_7.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_9.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_10)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_9.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_10)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_10.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_10.addWidget(self.textEdit, 2, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_9.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_10.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 2, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_10.addWidget(self.pushButton_12, 3, 1, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_9)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_10.addWidget(self.toolButton_4, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_11.addWidget(self.textEdit_2, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_11.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_11.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "高级设置"))
        self.groupBox_4.setTitle(_translate("Form", "xss配置"))
        self.label_18.setText(_translate("Form", "是否扫描仅能在 ie 下利用的 xss"))
        self.checkBox_31.setText(_translate("Form", "detect_xss_in_cookie"))
        self.label_17.setText(_translate("Form", "是否探测入口点在 cookie 中的 xss"))
        self.checkBox_32.setText(_translate("Form", "ie_feature"))
        self.pushButton_7.setText(_translate("Form", "全选"))
        self.pushButton_8.setText(_translate("Form", "确认修改"))
        self.groupBox.setTitle(_translate("Form", "插件配置"))
        self.checkBox_11.setText(_translate("Form", "shiro"))
        self.checkBox_16.setText(_translate("Form", "upload"))
        self.checkBox_5.setText(_translate("Form", "dirscan"))
        self.checkBox_1.setText(_translate("Form", "baseline"))
        self.checkBox_14.setText(_translate("Form", "struts"))
        self.pushButton_2.setText(_translate("Form", "确认修改"))
        self.checkBox_3.setText(_translate("Form", "cmd-injection"))
        self.checkBox_8.setText(_translate("Form", "path-traversal"))
        self.pushButton.setText(_translate("Form", "全选"))
        self.checkBox_7.setText(_translate("Form", "jsonp"))
        self.checkBox_10.setText(_translate("Form", "redirect"))
        self.checkBox_13.setText(_translate("Form", "ssrf"))
        self.checkBox_19.setText(_translate("Form", "xstream"))
        self.checkBox_2.setText(_translate("Form", "brute-force"))
        self.checkBox_4.setText(_translate("Form", "crlf-injection"))
        self.checkBox_6.setText(_translate("Form", "fastjson"))
        self.checkBox_18.setText(_translate("Form", "xxe"))
        self.checkBox_12.setText(_translate("Form", "sqldet"))
        self.checkBox_15.setText(_translate("Form", "thinkphp"))
        self.checkBox_17.setText(_translate("Form", "xss"))
        self.checkBox_9.setText(_translate("Form", "phantasm"))
        self.groupBox_7.setTitle(_translate("Form", "shiro配置"))
        self.label_22.setText(_translate("Form", "自定义 shiro key"))
        self.label_21.setText(_translate("Form", "默认shiro cookie"))
        self.pushButton_13.setText(_translate("Form", "确认修改"))
        self.lineEdit_3.setText(_translate("Form", "rememberMe"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label_23.setText(_translate("Form", "选择shiro key文件"))
        self.groupBox_3.setTitle(_translate("Form", "sqldet配置"))
        self.checkBox_36.setText(_translate("Form", "use_comment_in_payload"))
        self.checkBox_37.setText(_translate("Form", "detect_sqli_in_cookie"))
        self.checkBox_33.setText(_translate("Form", "boolean_based_detection"))
        self.label_12.setText(_translate("Form", "是否检测布尔盲注"))
        self.checkBox_35.setText(_translate("Form", "time_based_detection"))
        self.checkBox_34.setText(_translate("Form", "error_based_detection"))
        self.pushButton_5.setText(_translate("Form", "全选"))
        self.pushButton_6.setText(_translate("Form", "确认修改"))
        self.label_13.setText(_translate("Form", "是否检测报错注入"))
        self.label_14.setText(_translate("Form", "是否检测时间盲注"))
        self.label_15.setText(_translate("Form", "是否在时间盲注中使用comment，建议不开"))
        self.label_16.setText(_translate("Form", "是否检查在 cookie 中的注入"))
        self.groupBox_5.setTitle(_translate("Form", "设置"))
        self.pushButton_9.setText(_translate("Form", "一键恢复默认设置"))
        self.groupBox_2.setTitle(_translate("Form", "baseline配置"))
        self.checkBox_23.setText(_translate("Form", "detect_system_path_leak"))
        self.label_6.setText(_translate("Form", "检查 http 安全相关 header 是否配置"))
        self.checkBox_29.setText(_translate("Form", "detect_china_bank_card"))
        self.label_8.setText(_translate("Form", "检查响应是否存在身份证号"))
        self.label_10.setText(_translate("Form", "检查响应是否存在银行卡号"))
        self.label_9.setText(_translate("Form", "检查响应是否存在电话号码"))
        self.label_4.setText(_translate("Form", "检查响应是否包含系统路径泄露"))
        self.checkBox_22.setText(_translate("Form", "detect_phpinfo"))
        self.checkBox_27.setText(_translate("Form", "detect_china_id_card_number"))
        self.checkBox_24.setText(_translate("Form", "detect_outdated_ssl_version"))
        self.checkBox_21.setText(_translate("Form", "detect_server_error_page"))
        self.label_7.setText(_translate("Form", "检查 set-cookie 时是否设置 http only"))
        self.label.setText(_translate("Form", "检查 cors 相关配置"))
        self.checkBox_25.setText(_translate("Form", "detect_http_header_config"))
        self.label_5.setText(_translate("Form", "检查 ssl 版本问题"))
        self.label_2.setText(_translate("Form", "检查服务器错误信息"))
        self.label_3.setText(_translate("Form", "检查响应是否包含phpinfo"))
        self.label_11.setText(_translate("Form", "检查响应是否包含内网 ip"))
        self.checkBox_26.setText(_translate("Form", "detect_cookie_httponly"))
        self.checkBox_30.setText(_translate("Form", "detect_private_ip"))
        self.checkBox_20.setText(_translate("Form", "detect_cors_header_config"))
        self.checkBox_28.setText(_translate("Form", "detect_china_phone_number"))
        self.pushButton_3.setText(_translate("Form", "全选"))
        self.pushButton_4.setText(_translate("Form", "确认修改"))
        self.groupBox_6.setTitle(_translate("Form", "headers配置"))
        self.lineEdit.setText(_translate("Form", "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"))
        self.label_19.setText(_translate("Form", "User-Agent"))
        self.label_20.setText(_translate("Form", "Cookie"))
        self.pushButton_10.setText(_translate("Form", "确认修改"))
        self.groupBox_10.setTitle(_translate("Form", "brute-force配置"))
        self.label_25.setText(_translate("Form", "选择密码字典"))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.pushButton_11.setText(_translate("Form", "确认修改"))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.label_24.setText(_translate("Form", "选择用户字典"))
        self.groupBox_9.setTitle(_translate("Form", "dirscan配置"))
        self.label_26.setText(_translate("Form", "输入检测深度(0-9)"))
        self.label_27.setText(_translate("Form", "自定义字典"))
        self.lineEdit_8.setText(_translate("Form", "1"))
        self.label_28.setText(_translate("Form", "想要排除的内部的扫描category，例如[sensitive/crossdomain,  system/key]"))
        self.pushButton_12.setText(_translate("Form", "确认修改"))
        self.toolButton_4.setText(_translate("Form", "..."))
        self.groupBox_8.setTitle(_translate("Form", "phantasm配置"))
        self.label_29.setText(_translate("Form", "输入检测深度(0-9)"))
        self.label_30.setText(_translate("Form", "排除哪些 poc, 支持 glob 语法, 如: /home/poc/*thinkphp* 或 poc-yaml-weblogic*"))
        self.lineEdit_10.setText(_translate("Form", "1"))
        self.pushButton_14.setText(_translate("Form", "确认修改"))
